# Name of the DBT Project
name: 'my_dbt_project'
version: '1.0.0'

# Profile name (must match profiles.yml)
profile: 'my_dbt_project'

# Define paths for different dbt file types
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

# Folders to clean when running `dbt clean`
clean-targets:
  - "target"
  - "dbt_packages"

models:
  my_dbt_project:
    staging:  # Grouping staging models
      +schema: processing_dbt_schema
      +materialized: view  # Assuming they are views
      customers_stg:
        +materialized: view
      orders_stg:
        +materialized: view
      order_items_stg:
        +materialized: view
      orders_fact_stg:
        +materialized: table
    marts:
      +schema: my_dbt_schema
      +materialized: table
      customer_revenue:
        +materialized: table




